name: Nova Build Wheels (Windows)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .ci/**/*
      - .github/workflows/build-wheels-windows.yml
      - pyproject.toml
      - setup.py
    tags:
      - ciflow/binaries/*
  push:
    tags:
      - release/*
  tags:
      # NOTE: Binary build pipelines should only get triggered on release candidate builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
      - ciflow/binaries/*
  release:
    types: [published]

jobs:
  generate-matrix:
    name: Generate Windows matrix
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: wheel
      os: windows
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      with-cuda: disable
      with-rocm: disable
      with-cpu: enable
      with-xpu: disable
      python-versions: ${{ env.PYTHON_VERSIONS_JSON }}

  build:
    name: Build Windows wheels
    needs: generate-matrix
    uses: pytorch/test-infra/.github/workflows/build_wheels_windows.yml@main
    with:
      repository: meta-pytorch/tokenizers
      ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      trigger-event: ${{ github.event_name }}
      package-name: pytorch_tokenizers
      smoke-test-script: .ci/scripts/wheel/test_wheel.py
